[project]
name = "billabot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyodbc>=5.2.0",
    "pyside6>=6.9.1",
    "sqlalchemy>=2.0.43",
]
